project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: intro.html
        text: Introduction
      - href: methodology.html
        text: Methodology
      - href: analysis.html
        text: Analysis
      - href: finding.html
        text: Results & Discussionuse
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

